import { AttachmentBuilder } from "discord.js";

export const stare = new AttachmentBuilder("./assets/krystal/greetings/stare.png").setName("FEAR.png");
export const kill = new AttachmentBuilder("./assets/krystal/kill/kill.png").setName("Kill.png");
export const yeet = new AttachmentBuilder("./assets/krystal/yeet/yeet.gif").setName("Yeet.gif");
export const pfft = new AttachmentBuilder("./assets/krystal/pfft.png").setName("PFFT.png");
export const run = new AttachmentBuilder("./assets/krystal/runngun.png").setName("Run and gun.png");
export const drown = new AttachmentBuilder("./assets/krystal/drown/drown.png").setName("Drown.png");
export const fire = new AttachmentBuilder("./assets/krystal/fire/fire.png").setName("Fire.png");
export const fireball = new AttachmentBuilder("./assets/krystal/fire/fireball.png").setName("fireball.png");
export const fly = new AttachmentBuilder("./assets/krystal/fly/fly.png").setName("Fly.png");
export const pride = new AttachmentBuilder("./assets/krystal/pride.png").setName("Pride.png");
export const glitch = new AttachmentBuilder("./assets/krystal/glitch.png").setName("Glitch.png");
export const inhale = new AttachmentBuilder("./assets/krystal/inhale.png").setName("Inhale.png");
export const moe = new AttachmentBuilder("./assets/krystal/moe.gif").setName("Moe.gif");
export const patreon = new AttachmentBuilder("./assets/krystal/patreon.png").setName("Patreon.png");
export const spin = new AttachmentBuilder("./assets/krystal/spin.png").setName("Spin.png");
export const swim = new AttachmentBuilder("./assets/krystal/swim/swim.png").setName("Swim.png");
export const swimsadie = new AttachmentBuilder("./assets/krystal/swim/swimsadie.png").setName("Swim.png");
export const throwUp = new AttachmentBuilder("./assets/krystal/throwUp.png").setName("ThrowUp.png");
export const vanquishFly = new AttachmentBuilder("./assets/krystal/fly/vanquishFly.gif").setName("VanquishFly.gif");
export const absorb = new AttachmentBuilder("./assets/krystal/absorb/absorb.png").setName("Absorb.png");
export const box = new AttachmentBuilder("./assets/krystal/box/box.gif").setName("Box.gif");
export const sleep = new AttachmentBuilder("./assets/krystal/sleep/sleep.png").setName("Sleep.png");
export const lamp = new AttachmentBuilder("./assets/krystal/lamp/lamp.png").setName("Lamp.png");
export const speak = new AttachmentBuilder("./assets/krystal/lamp/speak.gif").setName("Speak.gif");
export const popcorn = new AttachmentBuilder("./assets/krystal/popcorn/popcorn.png").setName("Popcorn.png");
export const beat = new AttachmentBuilder("./assets/ray/beat/beat.png").setName("Meat beating.png");

export const kick = new AttachmentBuilder("./assets/sadie/kick/kick.png").setName("Kick.png");
export const punch = new AttachmentBuilder("./assets/sadie/punch/punch.gif").setName("Punch.gif");
