import { MessageAttachment } from "discord.js";

export const stare = new MessageAttachment("./assets/krystal/greetings/stare.png", "FEAR.png");
export const kill = new MessageAttachment("./assets/krystal/kill/kill.png", "Kill.png");
export const yeet = new MessageAttachment("./assets/krystal/yeet/yeet.gif", "Yeet.gif");
export const pfft = new MessageAttachment("./assets/krystal/pfft.png", "PFFT.png");
export const run = new MessageAttachment("./assets/krystal/runngun.png", "Run and gun.png");
export const drown = new MessageAttachment("./assets/krystal/drown/drown.png", "Drown.png");
export const fire = new MessageAttachment("./assets/krystal/fire/fire.png", "Fire.png");
export const fireball = new MessageAttachment("./assets/krystal/fire/fireball.png", "fireball.png");
export const fly = new MessageAttachment("./assets/krystal/fly/fly.png", "Fly.png");
export const pride = new MessageAttachment("./assets/krystal/pride.png", "Pride.png");
export const glitch = new MessageAttachment("./assets/krystal/glitch.png", "Glitch.png");
export const inhale = new MessageAttachment("./assets/krystal/inhale.png", "Inhale.png");
export const moe = new MessageAttachment("./assets/krystal/moe.gif", "Moe.gif");
export const patreon = new MessageAttachment("./assets/krystal/patreon.png", "Patreon.png");
export const spin = new MessageAttachment("./assets/krystal/spin.png", "Spin.png");
export const swim = new MessageAttachment("./assets/krystal/swim/swim.png", "Swim.png");
export const swimsadie = new MessageAttachment("./assets/krystal/swim/swimsadie.png", "Swim.png");
export const throwUp = new MessageAttachment("./assets/krystal/throwUp.png", "ThrowUp.png");
export const vanquishFly = new MessageAttachment("./assets/krystal/fly/vanquishFly.gif", "VanquishFly.gif");
export const absorb = new MessageAttachment("./assets/krystal/absorb/absorb.png", "Absorb.png");
export const box = new MessageAttachment("./assets/krystal/box/box.png", "Box.png");
export const sleep = new MessageAttachment("./assets/krystal/sleep/sleep.png", "Sleep.png");
export const lamp = new MessageAttachment("./assets/krystal/lamp/lamp.png", "Lamp.png");
export const speak = new MessageAttachment("./assets/krystal/lamp/speak.gif", "Speak.gif");
export const popcorn = new MessageAttachment("./assets/krystal/popcorn/popcorn.png", "Popcorn.png");
export const beat = new MessageAttachment("./assets/ray/beat/beat.png", "Meat beating.png");

export const kick = new MessageAttachment("./assets/sadie/kick/kick.png", "Kick.png");
export const punch = new MessageAttachment("./assets/sadie/punch/punch.gif", "Punch.gif");
